function createfigure(X1, X2, YMatrix1)
%CREATEFIGURE(X1, X2, YMATRIX1)
%  X1:  vector of x data
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 30-Dec-2018 17:30:36

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,X1,'Color',[0 0 1]);

% Create multiple lines using matrix input to plot
plot1 = plot(X2,YMatrix1,'Marker','x','LineStyle','none');
set(plot1(1),'Color',[0 0 1]);
set(plot1(2),'MarkerSize',10,'LineWidth',2,'Color',[0 0 0]);

% Create xlabel
xlabel('Cross-lingual Embedding (Aligned FastText)','FontSize',24);

% Create ylabel
ylabel('CLESA','FontSize',24);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',24);



